spring.application.name=cinetrack
# Server
server.port=8080

# Database ? update these to match your MySQL Docker setup
spring.datasource.url=jdbc:mysql://localhost:33306/cinetrack
spring.datasource.username=root
spring.datasource.password=mysqlpass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Mustache
spring.mustache.cache=false
spring.mustache.suffix=.mustache

# Session
server.servlet.session.timeout=30m